GET http://localhost:3000/api/offers
Content-Type: application/json

###

POST http://localhost:3000/api/offers
Content-Type: application/json

{
  "description": "Текст объявления. Минимум 50 символов, максимум 1000",
  "picture": "picture.jpg",
  "title": "Заголовок объявления",
  "type": "offer",
  "sum": 100,
  "category": [
    "Книги",
    "Животные"
  ]
}

###

PUT http://localhost:3000/api/offers/zIisjO
Content-Type: application/json

{
  "title": "Заголовок отредактированного объявления"
}

###

DELETE http://localhost:3000/api/offers/52B5rg
Content-Type: application/json

###

GET http://localhost:3000/api/offers/V4ObMH/comments
Content-Type: application/json

###

DELETE http://localhost:3000/api/offers/7d8tO4/comments/HobK7r
Content-Type: application/json

###

POST http://localhost:3000/api/offers/GwWynF/comments
Content-Type: application/json

{
  "text": "Текст комментария с двадцатью символами"
}

###

GET http://localhost:3000/api/search?query=журналов
Content-Type: application/json

###
